# Generated by Django 5.1.3 on 2024-11-28 11:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqomlarmodel',
            name='maqom_sozlari',
            field=ckeditor.fields.RichTextField(verbose_name="Maqom so'zlari"),
        ),
    ]
