# Generated by Django 5.1.3 on 2024-11-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_maqomlarmodel_maqom_sozlari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maqomlarmodel',
            name='maqom_yartuvchisi',
        ),
    ]
